<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/generate_adod_factions.py; do not hand-edit, edit the SPEC and regenerate -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="no" indent="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>


	<!-- House Martell: Doran Martell -->
	<xsl:template match="NPCCharacter[@id='lord_3_1']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_aserai_1}Doran Martell</xsl:attribute>
	</xsl:template>

	<!-- House Vaith: Daeron Vaith -->
	<xsl:template match="NPCCharacter[@id='lord_3_16']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_aserai_4}Daeron Vaith</xsl:attribute>
	</xsl:template>

	<!-- House Yronwood: Ormond Yronwood -->
	<xsl:template match="NPCCharacter[@id='lord_3_17']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_aserai_5}Ormond Yronwood</xsl:attribute>
	</xsl:template>

	<!-- House Manwoody: Dagos Manwoody -->
	<xsl:template match="NPCCharacter[@id='lord_3_19']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_aserai_7}Dagos Manwoody</xsl:attribute>
	</xsl:template>

	<!-- House Stark: Eddard Stark -->
	<xsl:template match="NPCCharacter[@id='lord_5_1']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_1}Eddard Stark</xsl:attribute>
	</xsl:template>

	<!-- The Night's Watch: Lord Commander Qorgyle -->
	<xsl:template match="NPCCharacter[@id='lord_5_3']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_2}Lord Commander Qorgyle</xsl:attribute>
	</xsl:template>

	<!-- House Reed: Howland Reed -->
	<xsl:template match="NPCCharacter[@id='lord_5_5']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_3}Howland Reed</xsl:attribute>
	</xsl:template>

	<!-- House Manderly: Wyman Manderly -->
	<xsl:template match="NPCCharacter[@id='lord_5_14']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_4}Wyman Manderly</xsl:attribute>
	</xsl:template>

	<!-- House Umber: Jon Umber -->
	<xsl:template match="NPCCharacter[@id='lord_5_16']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_5}Jon Umber</xsl:attribute>
	</xsl:template>

	<!-- The Shadow Tower Garrison: Denys Mallister -->
	<xsl:template match="NPCCharacter[@id='lord_5_17']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_6}Denys Mallister</xsl:attribute>
	</xsl:template>

	<!-- House Glover: Galbart Glover -->
	<xsl:template match="NPCCharacter[@id='lord_5_15']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_7}Galbart Glover</xsl:attribute>
	</xsl:template>

	<!-- House Mormont: Jeor Mormont -->
	<xsl:template match="NPCCharacter[@id='lord_B8_l']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_battania_8}Jeor Mormont</xsl:attribute>
	</xsl:template>

	<!-- House Royce: Yohn Royce -->
	<xsl:template match="NPCCharacter[@id='lord_1_1']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_1}Yohn Royce</xsl:attribute>
	</xsl:template>

	<!-- House Tully: Hoster Tully -->
	<xsl:template match="NPCCharacter[@id='lord_1_3']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_2}Hoster Tully</xsl:attribute>
	</xsl:template>

	<!-- House Frey: Walder Frey -->
	<xsl:template match="NPCCharacter[@id='lord_1_5']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_3}Walder Frey</xsl:attribute>
	</xsl:template>

	<!-- House Corbray: Lyonel Corbray -->
	<xsl:template match="NPCCharacter[@id='lord_1_20']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_4}Lyonel Corbray</xsl:attribute>
	</xsl:template>

	<!-- House Vance of Atranta: Norbert Vance -->
	<xsl:template match="NPCCharacter[@id='lord_1_50']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_5}Norbert Vance</xsl:attribute>
	</xsl:template>

	<!-- House Hunter: Eon Hunter -->
	<xsl:template match="NPCCharacter[@id='lord_1_51']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_6}Eon Hunter</xsl:attribute>
	</xsl:template>

	<!-- House Mallister: Jason Mallister -->
	<xsl:template match="NPCCharacter[@id='lord_1_58']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_7}Jason Mallister</xsl:attribute>
	</xsl:template>

	<!-- House Blackwood: Tytos Blackwood -->
	<xsl:template match="NPCCharacter[@id='lord_NE8_l']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_8}Tytos Blackwood</xsl:attribute>
	</xsl:template>

	<!-- House Mooton: William Mooton -->
	<xsl:template match="NPCCharacter[@id='lord_NE9_l']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_north_9}William Mooton</xsl:attribute>
	</xsl:template>

	<!-- House Targaryen of Dragonstone: Willem Darry -->
	<xsl:template match="NPCCharacter[@id='lord_1_14']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_south_1}Willem Darry</xsl:attribute>
	</xsl:template>

	<!-- House Bolton: Roose Bolton -->
	<xsl:template match="NPCCharacter[@id='lord_1_17']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_south_3}Roose Bolton</xsl:attribute>
	</xsl:template>

	<!-- House Antaryon: Ferrego Antaryon -->
	<xsl:template match="NPCCharacter[@id='lord_1_30']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_south_4}Ferrego Antaryon</xsl:attribute>
	</xsl:template>

	<!-- House Selmy: Arstan Selmy -->
	<xsl:template match="NPCCharacter[@id='lord_1_55']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_south_7}Arstan Selmy</xsl:attribute>
	</xsl:template>

	<!-- House Tyrell: Mace Tyrell -->
	<xsl:template match="NPCCharacter[@id='lord_1_7']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_west_1}Mace Tyrell</xsl:attribute>
	</xsl:template>

	<!-- House Baratheon: Robert Baratheon -->
	<xsl:template match="NPCCharacter[@id='lord_1_9']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_west_2}Robert Baratheon</xsl:attribute>
	</xsl:template>

	<!-- House Buckler: Ralph Buckler -->
	<xsl:template match="NPCCharacter[@id='lord_1_40']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_west_4}Ralph Buckler</xsl:attribute>
	</xsl:template>

	<!-- House Tarth: Selwyn Tarth -->
	<xsl:template match="NPCCharacter[@id='lord_1_45']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_west_5}Selwyn Tarth</xsl:attribute>
	</xsl:template>

	<!-- House Velaryon: Lucerys Velaryon -->
	<xsl:template match="NPCCharacter[@id='lord_1_52']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_west_6}Lucerys Velaryon</xsl:attribute>
	</xsl:template>

	<!-- House Ashford: Androw Ashford -->
	<xsl:template match="NPCCharacter[@id='lord_1_71']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_empire_west_8}Androw Ashford</xsl:attribute>
	</xsl:template>

	<!-- House Greyjoy: Quellon Greyjoy -->
	<xsl:template match="NPCCharacter[@id='lord_2_1']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_sturgia_1}Quellon Greyjoy</xsl:attribute>
	</xsl:template>

	<!-- House Harlaw: Rodrik Harlaw -->
	<xsl:template match="NPCCharacter[@id='lord_2_5']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_sturgia_3}Rodrik Harlaw</xsl:attribute>
	</xsl:template>

	<!-- House Dayne: Aron Dayne -->
	<xsl:template match="NPCCharacter[@id='lord_2_16']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_sturgia_4}Aron Dayne</xsl:attribute>
	</xsl:template>

	<!-- House Karstark: Rickard Karstark -->
	<xsl:template match="NPCCharacter[@id='lord_2_18']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_sturgia_6}Rickard Karstark</xsl:attribute>
	</xsl:template>

	<!-- House Goodbrother: Gorold Goodbrother -->
	<xsl:template match="NPCCharacter[@id='lord_2_20']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_sturgia_8}Gorold Goodbrother</xsl:attribute>
	</xsl:template>

	<!-- House Lannister: Tywin Lannister -->
	<xsl:template match="NPCCharacter[@id='lord_4_1']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_1}Tywin Lannister</xsl:attribute>
	</xsl:template>

	<!-- House Rykker: Renfred Rykker -->
	<xsl:template match="NPCCharacter[@id='lord_4_28']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_10}Renfred Rykker</xsl:attribute>
	</xsl:template>

	<!-- House Redwyne: Paxter Redwyne -->
	<xsl:template match="NPCCharacter[@id='lord_V11_l']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_11}Paxter Redwyne</xsl:attribute>
	</xsl:template>

	<!-- House Tarly: Randyll Tarly -->
	<xsl:template match="NPCCharacter[@id='lord_4_3']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_2}Randyll Tarly</xsl:attribute>
	</xsl:template>

	<!-- House Arryn: Jon Arryn -->
	<xsl:template match="NPCCharacter[@id='lord_4_6']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_3}Jon Arryn</xsl:attribute>
	</xsl:template>

	<!-- House Hightower: Leyton Hightower -->
	<xsl:template match="NPCCharacter[@id='lord_4_16']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_4}Leyton Hightower</xsl:attribute>
	</xsl:template>

	<!-- House Lefford: Leo Lefford -->
	<xsl:template match="NPCCharacter[@id='lord_4_22']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_6}Leo Lefford</xsl:attribute>
	</xsl:template>

	<!-- House Kenning of Kayce: Terrence Kenning -->
	<xsl:template match="NPCCharacter[@id='lord_4_23']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_7}Terrence Kenning</xsl:attribute>
	</xsl:template>

	<!-- House Swyft: Harys Swyft -->
	<xsl:template match="NPCCharacter[@id='lord_4_24']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_8}Harys Swyft</xsl:attribute>
	</xsl:template>

	<!-- House Crakehall: Sumner Crakehall -->
	<xsl:template match="NPCCharacter[@id='lord_4_27']/@name">
		<xsl:attribute name="name">{=dots_ruler_clan_vlandia_9}Sumner Crakehall</xsl:attribute>
	</xsl:template>
</xsl:stylesheet>
