<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/generate_adod_factions.py; do not hand-edit, edit the SPEC and regenerate -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="no" indent="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>


	<!-- House Martell -->
	<xsl:template match="Faction[@id='clan_aserai_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_1_name}House Martell</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_1']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A2</xsl:attribute>
	</xsl:template>

	<!-- House Draqios -->
	<xsl:template match="Faction[@id='clan_aserai_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_2_name}House Draqios</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_2']/@culture">
		<xsl:attribute name="culture">Culture.Myrish</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.myr</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NOX_ADOD5</xsl:attribute>
	</xsl:template>

	<!-- House Narratys -->
	<xsl:template match="Faction[@id='clan_aserai_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_3_name}House Narratys</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_3']/@culture">
		<xsl:attribute name="culture">Culture.Pentoshi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.pentos</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_NOX_town_K6</xsl:attribute>
	</xsl:template>

	<!-- House Vaith -->
	<xsl:template match="Faction[@id='clan_aserai_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_4_name}House Vaith</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NoxixDorne_nox4</xsl:attribute>
	</xsl:template>

	<!-- House Yronwood -->
	<xsl:template match="Faction[@id='clan_aserai_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_5_name}House Yronwood</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_5']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A3</xsl:attribute>
	</xsl:template>

	<!-- House Vhassyl -->
	<xsl:template match="Faction[@id='clan_aserai_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_6_name}House Vhassyl</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_6']/@culture">
		<xsl:attribute name="culture">Culture.Lyseni</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.lys</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFLys1</xsl:attribute>
	</xsl:template>

	<!-- House Manwoody -->
	<xsl:template match="Faction[@id='clan_aserai_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_7_name}House Manwoody</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A5</xsl:attribute>
	</xsl:template>

	<!-- House Adarys -->
	<xsl:template match="Faction[@id='clan_aserai_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_8_name}House Adarys</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_8']/@culture">
		<xsl:attribute name="culture">Culture.Tyroshi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_8']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.tyrosh</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NOX_ADOD6</xsl:attribute>
	</xsl:template>

	<!-- Khalasar of Khal Drogo -->
	<xsl:template match="Faction[@id='clan_aserai_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_aserai_9_name}Khalasar of Khal Drogo</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_9']/@culture">
		<xsl:attribute name="culture">Culture.Dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_9']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_aserai_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NOX_ADOD3</xsl:attribute>
	</xsl:template>

	<!-- House Stark -->
	<xsl:template match="Faction[@id='clan_battania_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_1_name}House Stark</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_1']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B1</xsl:attribute>
	</xsl:template>

	<!-- The Night's Watch -->
	<xsl:template match="Faction[@id='clan_battania_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_2_name}The Night's Watch</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_2']/@culture">
		<xsl:attribute name="culture">Culture.nightswatch</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.nightswatch</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_2']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_S5</xsl:attribute>
	</xsl:template>

	<!-- House Reed -->
	<xsl:template match="Faction[@id='clan_battania_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_3_name}House Reed</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFNorth1</xsl:attribute>
	</xsl:template>

	<!-- House Manderly -->
	<xsl:template match="Faction[@id='clan_battania_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_4_name}House Manderly</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_4']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B5</xsl:attribute>
	</xsl:template>

	<!-- House Umber -->
	<xsl:template match="Faction[@id='clan_battania_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_5_name}House Umber</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B4</xsl:attribute>
	</xsl:template>

	<!-- The Shadow Tower Garrison -->
	<xsl:template match="Faction[@id='clan_battania_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_6_name}The Shadow Tower Garrison</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_6']/@culture">
		<xsl:attribute name="culture">Culture.nightswatch</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.nightswatch</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_6']/@tier">
		<xsl:attribute name="tier">4</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_S7</xsl:attribute>
	</xsl:template>

	<!-- House Glover -->
	<xsl:template match="Faction[@id='clan_battania_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_7_name}House Glover</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B6</xsl:attribute>
	</xsl:template>

	<!-- House Mormont -->
	<xsl:template match="Faction[@id='clan_battania_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_battania_8_name}House Mormont</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_battania_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_B6</xsl:attribute>
	</xsl:template>

	<!-- House Royce -->
	<xsl:template match="Faction[@id='clan_empire_north_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_1_name}House Royce</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_1']/@culture">
		<xsl:attribute name="culture">Culture.Valeman</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_1']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire_s</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_1']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NoxixValeExpansion_nox2</xsl:attribute>
	</xsl:template>

	<!-- House Tully -->
	<xsl:template match="Faction[@id='clan_empire_north_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_2_name}House Tully</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_2']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_2']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_V1</xsl:attribute>
	</xsl:template>

	<!-- House Frey -->
	<xsl:template match="Faction[@id='clan_empire_north_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_3_name}House Frey</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_3']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_3']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFRiver1</xsl:attribute>
	</xsl:template>

	<!-- House Corbray -->
	<xsl:template match="Faction[@id='clan_empire_north_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_4_name}House Corbray</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_4']/@culture">
		<xsl:attribute name="culture">Culture.Valeman</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_4']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire_s</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFVale1</xsl:attribute>
	</xsl:template>

	<!-- House Vance of Atranta -->
	<xsl:template match="Faction[@id='clan_empire_north_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_5_name}House Vance of Atranta</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_5']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_5']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFRiver3</xsl:attribute>
	</xsl:template>

	<!-- House Hunter -->
	<xsl:template match="Faction[@id='clan_empire_north_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_6_name}House Hunter</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_6']/@culture">
		<xsl:attribute name="culture">Culture.Valeman</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire_s</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_EN5</xsl:attribute>
	</xsl:template>

	<!-- House Mallister -->
	<xsl:template match="Faction[@id='clan_empire_north_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_7_name}House Mallister</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_7']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_7']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_V4</xsl:attribute>
	</xsl:template>

	<!-- House Blackwood -->
	<xsl:template match="Faction[@id='clan_empire_north_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_8_name}House Blackwood</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_8']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_8']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_V5</xsl:attribute>
	</xsl:template>

	<!-- House Mooton -->
	<xsl:template match="Faction[@id='clan_empire_north_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_north_9_name}House Mooton</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_9']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_9']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_north_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ES7</xsl:attribute>
	</xsl:template>

	<!-- House Targaryen of Dragonstone -->
	<xsl:template match="Faction[@id='clan_empire_south_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_1_name}House Targaryen of Dragonstone</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_1']/@culture">
		<xsl:attribute name="culture">Culture.valyrian</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_1']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_1']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_town_dragonstone</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_1']/@color">
		<xsl:attribute name="color">FF1C1C1C</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_1']/@color2">
		<xsl:attribute name="color2">FFC0392B</xsl:attribute>
	</xsl:template>

	<!-- House Maegyr -->
	<xsl:template match="Faction[@id='clan_empire_south_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_2_name}House Maegyr</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_2']/@culture">
		<xsl:attribute name="culture">Culture.Volantene</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.volantis</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_NOXIX_town_A2</xsl:attribute>
	</xsl:template>

	<!-- House Bolton -->
	<xsl:template match="Faction[@id='clan_empire_south_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_3_name}House Bolton</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_3']/@culture">
		<xsl:attribute name="culture">Culture.battania</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.battania</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_3']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B2</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_3']/@color">
		<xsl:attribute name="color">FF8B3A62</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_3']/@color2">
		<xsl:attribute name="color2">FFC0392B</xsl:attribute>
	</xsl:template>

	<!-- House Antaryon -->
	<xsl:template match="Faction[@id='clan_empire_south_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_4_name}House Antaryon</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_4']/@culture">
		<xsl:attribute name="culture">Culture.Braavosi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_4']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.braavos</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_4']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_NOX_town_K3</xsl:attribute>
	</xsl:template>

	<!-- House Eqevaro -->
	<xsl:template match="Faction[@id='clan_empire_south_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_5_name}House Eqevaro</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_5']/@culture">
		<xsl:attribute name="culture">Culture.Lorathi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_5']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.lorath</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_NOX_town_K4</xsl:attribute>
	</xsl:template>

	<!-- House Vhassar of Volantis -->
	<xsl:template match="Faction[@id='clan_empire_south_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_6_name}House Vhassar of Volantis</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_6']/@culture">
		<xsl:attribute name="culture">Culture.Volantene</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.volantis</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFVolantis3</xsl:attribute>
	</xsl:template>

	<!-- House Selmy -->
	<xsl:template match="Faction[@id='clan_empire_south_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_7_name}House Selmy</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_7']/@culture">
		<xsl:attribute name="culture">Culture.Stormlander</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_7']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire_w</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_NOX_ADOD5</xsl:attribute>
	</xsl:template>

	<!-- House Paenymion -->
	<xsl:template match="Faction[@id='clan_empire_south_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_8_name}House Paenymion</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_8']/@culture">
		<xsl:attribute name="culture">Culture.Volantene</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_8']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.volantis</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFVolantis2</xsl:attribute>
	</xsl:template>

	<!-- House Prestayn -->
	<xsl:template match="Faction[@id='clan_empire_south_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_south_9_name}House Prestayn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_9']/@culture">
		<xsl:attribute name="culture">Culture.Braavosi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_9']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.braavos</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_south_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFBraavos2</xsl:attribute>
	</xsl:template>

	<!-- House Tyrell -->
	<xsl:template match="Faction[@id='clan_empire_west_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_1_name}House Tyrell</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_1']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_1']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_1']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EW1</xsl:attribute>
	</xsl:template>

	<!-- House Baratheon -->
	<xsl:template match="Faction[@id='clan_empire_west_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_2_name}House Baratheon</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_2']/@culture">
		<xsl:attribute name="culture">Culture.Stormlander</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_2']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ES1</xsl:attribute>
	</xsl:template>

	<!-- House Xhoan -->
	<xsl:template match="Faction[@id='clan_empire_west_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_3_name}House Xhoan</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_3']/@culture">
		<xsl:attribute name="culture">Culture.Qartheen</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.qarth</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_KR4</xsl:attribute>
	</xsl:template>

	<!-- House Buckler -->
	<xsl:template match="Faction[@id='clan_empire_west_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_4_name}House Buckler</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_4']/@culture">
		<xsl:attribute name="culture">Culture.Stormlander</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_castle_ES1</xsl:attribute>
	</xsl:template>

	<!-- House Tarth -->
	<xsl:template match="Faction[@id='clan_empire_west_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_5_name}House Tarth</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_5']/@culture">
		<xsl:attribute name="culture">Culture.Stormlander</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ES2</xsl:attribute>
	</xsl:template>

	<!-- House Velaryon -->
	<xsl:template match="Faction[@id='clan_empire_west_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_6_name}House Velaryon</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_6']/@culture">
		<xsl:attribute name="culture">Culture.valyrian</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_6']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EN5</xsl:attribute>
	</xsl:template>

	<!-- House Footly -->
	<xsl:template match="Faction[@id='clan_empire_west_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_7_name}House Footly</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_7']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_7']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EW6</xsl:attribute>
	</xsl:template>

	<!-- House Ashford -->
	<xsl:template match="Faction[@id='clan_empire_west_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_8_name}House Ashford</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_8']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_8']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EW4</xsl:attribute>
	</xsl:template>

	<!-- House Alesander -->
	<xsl:template match="Faction[@id='clan_empire_west_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_empire_west_9_name}House Alesander</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_9']/@culture">
		<xsl:attribute name="culture">Culture.Sarnori</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_9']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.sarnor</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_empire_west_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_town_ES7</xsl:attribute>
	</xsl:template>

	<!-- Khalasar of Khal Moro -->
	<xsl:template match="Faction[@id='clan_khuzait_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_1_name}Khalasar of Khal Moro</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_1']/@culture">
		<xsl:attribute name="culture">Culture.Dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_1']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_K5</xsl:attribute>
	</xsl:template>

	<!-- House Uhoris -->
	<xsl:template match="Faction[@id='clan_khuzait_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_2_name}House Uhoris</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_2']/@culture">
		<xsl:attribute name="culture">Culture.Tyroshi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.tyrosh</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFTyrosh1</xsl:attribute>
	</xsl:template>

	<!-- House Darvos -->
	<xsl:template match="Faction[@id='clan_khuzait_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_3_name}House Darvos</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_3']/@culture">
		<xsl:attribute name="culture">Culture.Norvoshi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.norvos</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_NOX_town_K5</xsl:attribute>
	</xsl:template>

	<!-- Khalasar of Khal Jommo -->
	<xsl:template match="Faction[@id='clan_khuzait_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_4_name}Khalasar of Khal Jommo</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_4']/@culture">
		<xsl:attribute name="culture">Culture.Dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_4']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_K2</xsl:attribute>
	</xsl:template>

	<!-- House Vaqho -->
	<xsl:template match="Faction[@id='clan_khuzait_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_5_name}House Vaqho</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_5']/@culture">
		<xsl:attribute name="culture">Culture.Qohorik</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_5']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.qohor</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.ADOD_IAF_town_ES3</xsl:attribute>
	</xsl:template>

	<!-- Khalasar of Khal Pono -->
	<xsl:template match="Faction[@id='clan_khuzait_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_6_name}Khalasar of Khal Pono</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_6']/@culture">
		<xsl:attribute name="culture">Culture.Dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_K6</xsl:attribute>
	</xsl:template>

	<!-- House Vhalaso -->
	<xsl:template match="Faction[@id='clan_khuzait_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_7_name}House Vhalaso</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_7']/@culture">
		<xsl:attribute name="culture">Culture.Tyroshi</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_7']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.tyrosh</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFTyrosh2</xsl:attribute>
	</xsl:template>

	<!-- Khalasar of Khal Jhaqo -->
	<xsl:template match="Faction[@id='clan_khuzait_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_8_name}Khalasar of Khal Jhaqo</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_8']/@culture">
		<xsl:attribute name="culture">Culture.Dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_8']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_K3</xsl:attribute>
	</xsl:template>

	<!-- House Zhorenne -->
	<xsl:template match="Faction[@id='clan_khuzait_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_khuzait_9_name}House Zhorenne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_9']/@culture">
		<xsl:attribute name="culture">Culture.Qohorik</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_9']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.qohor</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_khuzait_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFQohor1</xsl:attribute>
	</xsl:template>

	<!-- House Greyjoy -->
	<xsl:template match="Faction[@id='clan_sturgia_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_1_name}House Greyjoy</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_1']/@culture">
		<xsl:attribute name="culture">Culture.Ironborn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_1']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.ironislands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_1']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A10</xsl:attribute>
	</xsl:template>

	<!-- The Whitetree Clans -->
	<xsl:template match="Faction[@id='clan_sturgia_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_2_name}The Whitetree Clans</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_2']/@culture">
		<xsl:attribute name="culture">Culture.freefolk</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.freefolk</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_S3</xsl:attribute>
	</xsl:template>

	<!-- House Harlaw -->
	<xsl:template match="Faction[@id='clan_sturgia_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_3_name}House Harlaw</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_3']/@culture">
		<xsl:attribute name="culture">Culture.Ironborn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.ironislands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_3']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NOX_ADOD7</xsl:attribute>
	</xsl:template>

	<!-- House Dayne -->
	<xsl:template match="Faction[@id='clan_sturgia_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_4_name}House Dayne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_4']/@culture">
		<xsl:attribute name="culture">Culture.aserai</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_4']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.aserai</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_4']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A4</xsl:attribute>
	</xsl:template>

	<!-- The Thenns -->
	<xsl:template match="Faction[@id='clan_sturgia_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_5_name}The Thenns</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_5']/@culture">
		<xsl:attribute name="culture">Culture.freefolk</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_5']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.freefolk</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_5']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAF_FreeFolkExpansion11</xsl:attribute>
	</xsl:template>

	<!-- House Karstark -->
	<xsl:template match="Faction[@id='clan_sturgia_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_6_name}House Karstark</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_6']/@culture">
		<xsl:attribute name="culture">Culture.battania</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_6']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.battania</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B3</xsl:attribute>
	</xsl:template>

	<!-- The Ruddy Hall Clan -->
	<xsl:template match="Faction[@id='clan_sturgia_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_7_name}The Ruddy Hall Clan</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_7']/@culture">
		<xsl:attribute name="culture">Culture.freefolk</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_7']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.freefolk</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_S4</xsl:attribute>
	</xsl:template>

	<!-- House Goodbrother -->
	<xsl:template match="Faction[@id='clan_sturgia_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_8_name}House Goodbrother</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_8']/@culture">
		<xsl:attribute name="culture">Culture.Ironborn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_8']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.ironislands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFIron2</xsl:attribute>
	</xsl:template>

	<!-- Khalasar of Khal Zekko -->
	<xsl:template match="Faction[@id='clan_sturgia_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_sturgia_9_name}Khalasar of Khal Zekko</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_9']/@culture">
		<xsl:attribute name="culture">Culture.Dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_9']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.dothraki</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_sturgia_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A8</xsl:attribute>
	</xsl:template>

	<!-- House Lannister -->
	<xsl:template match="Faction[@id='clan_vlandia_1']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_1_name}House Lannister</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_1']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_1']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFWest1</xsl:attribute>
	</xsl:template>

	<!-- House Rykker -->
	<xsl:template match="Faction[@id='clan_vlandia_10']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_10_name}House Rykker</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_10']/@culture">
		<xsl:attribute name="culture">Culture.empire</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_10']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_10']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EN6</xsl:attribute>
	</xsl:template>

	<!-- House Redwyne -->
	<xsl:template match="Faction[@id='clan_vlandia_11']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_11_name}House Redwyne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_11']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_11']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_11']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_11']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EW2</xsl:attribute>
	</xsl:template>

	<!-- House Tarly -->
	<xsl:template match="Faction[@id='clan_vlandia_2']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_2_name}House Tarly</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_2']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_2']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_2']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_2']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_NoxixReach_nox1</xsl:attribute>
	</xsl:template>

	<!-- House Arryn -->
	<xsl:template match="Faction[@id='clan_vlandia_3']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_3_name}House Arryn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_3']/@culture">
		<xsl:attribute name="culture">Culture.Valeman</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_3']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.empire_s</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_3']/@tier">
		<xsl:attribute name="tier">6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_3']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EN1</xsl:attribute>
	</xsl:template>

	<!-- House Hightower -->
	<xsl:template match="Faction[@id='clan_vlandia_4']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_4_name}House Hightower</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_4']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_4']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_4']/@tier">
		<xsl:attribute name="tier">5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_4']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EW3</xsl:attribute>
	</xsl:template>

	<!-- House Eranyos -->
	<xsl:template match="Faction[@id='clan_vlandia_5']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_5_name}House Eranyos</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_5']/@culture">
		<xsl:attribute name="culture">Culture.Lyseni</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_5']/@super_faction">
		<xsl:attribute name="super_faction">Kingdom.lys</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_5']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFLys3</xsl:attribute>
	</xsl:template>

	<!-- House Lefford -->
	<xsl:template match="Faction[@id='clan_vlandia_6']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_6_name}House Lefford</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_6']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_ADOD_IAFWest1</xsl:attribute>
	</xsl:template>

	<!-- House Kenning of Kayce -->
	<xsl:template match="Faction[@id='clan_vlandia_7']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_7_name}House Kenning of Kayce</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_7']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_V9</xsl:attribute>
	</xsl:template>

	<!-- House Swyft -->
	<xsl:template match="Faction[@id='clan_vlandia_8']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_8_name}House Swyft</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_8']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_KR4</xsl:attribute>
	</xsl:template>

	<!-- House Crakehall -->
	<xsl:template match="Faction[@id='clan_vlandia_9']/@name">
		<xsl:attribute name="name">{=dots_clan_clan_vlandia_9_name}House Crakehall</xsl:attribute>
	</xsl:template>
	<xsl:template match="Faction[@id='clan_vlandia_9']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.castle_KR3</xsl:attribute>
	</xsl:template>

	<!-- The Mountain Clans of the Vale -->
	<xsl:template match="Faction[@id='mountain_bandits']/@name">
		<xsl:attribute name="name">{=dots_clan_mountain_bandits_name}The Mountain Clans of the Vale</xsl:attribute>
	</xsl:template>
</xsl:stylesheet>
