<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/generate_adod_factions.py; do not hand-edit, edit the SPEC and regenerate -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="no" indent="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>


	<!-- The Iron Throne -->
	<xsl:template match="Kingdom[@id='empire']/@owner">
		<xsl:attribute name="owner">Hero.lord_ADOD_adodhouse_1_1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ES5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@culture">
		<xsl:attribute name="culture">Culture.empire</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@color">
		<xsl:attribute name="color">FF1C1C1C</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@color2">
		<xsl:attribute name="color2">FFC0392B</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff1c1c1c</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffc0392b</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@name">
		<xsl:attribute name="name">{=dots_kingdom_empire}The Iron Throne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_empire_short}Iron Throne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@title">
		<xsl:attribute name="title">{=dots_kingdom_empire_title}The Iron Throne of Westeros</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_empire_ruler}King</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/@text">
		<xsl:attribute name="text">{=dots_kingdom_empire_desc}The Iron Throne of Westeros</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.battania" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire_s" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire_w" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.sturgia" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>

	<!-- The North -->
	<xsl:template match="Kingdom[@id='battania']/@owner">
		<xsl:attribute name="owner">Hero.lord_5_1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_B1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@culture">
		<xsl:attribute name="culture">Culture.battania</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@color">
		<xsl:attribute name="color">FF6E7B8B</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@color2">
		<xsl:attribute name="color2">FFF5F5F5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff6e7b8b</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xfff5f5f5</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@name">
		<xsl:attribute name="name">{=dots_kingdom_battania}The North</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_battania_short}North</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@title">
		<xsl:attribute name="title">{=dots_kingdom_battania_title}Kingdom of the North</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_battania_ruler}Warden of the North</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/@text">
		<xsl:attribute name="text">{=dots_kingdom_battania_desc}Kingdom of the North</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='battania']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.aserai" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.khuzait" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>

	<!-- The Riverlands -->
	<xsl:template match="Kingdom[@id='sturgia']/@owner">
		<xsl:attribute name="owner">Hero.lord_1_3</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_V1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@culture">
		<xsl:attribute name="culture">Culture.sturgia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@color">
		<xsl:attribute name="color">FF1E4D8B</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@color2">
		<xsl:attribute name="color2">FFC0392B</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff1e4d8b</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffc0392b</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@name">
		<xsl:attribute name="name">{=dots_kingdom_sturgia}The Riverlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_sturgia_short}Riverlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@title">
		<xsl:attribute name="title">{=dots_kingdom_sturgia_title}The Riverlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_sturgia_ruler}Lord Paramount of the Trident</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/@text">
		<xsl:attribute name="text">{=dots_kingdom_sturgia_desc}The Riverlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='sturgia']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.aserai" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.khuzait" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>

	<!-- The Westerlands -->
	<xsl:template match="Kingdom[@id='vlandia']/@owner">
		<xsl:attribute name="owner">Hero.lord_4_1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ADOD_IAFWest1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@culture">
		<xsl:attribute name="culture">Culture.vlandia</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@color">
		<xsl:attribute name="color">FF8B0000</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@color2">
		<xsl:attribute name="color2">FFFFD700</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff8b0000</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffffd700</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@name">
		<xsl:attribute name="name">{=dots_kingdom_vlandia}The Westerlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_vlandia_short}Westerlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@title">
		<xsl:attribute name="title">{=dots_kingdom_vlandia_title}The Westerlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_vlandia_ruler}Warden of the West</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/@text">
		<xsl:attribute name="text">{=dots_kingdom_vlandia_desc}The Westerlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='vlandia']/relationships">
		<relationships>
		</relationships>
	</xsl:template>

	<!-- The Reach -->
	<xsl:template match="Kingdom[@id='khuzait']/@owner">
		<xsl:attribute name="owner">Hero.lord_1_7</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EW1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@culture">
		<xsl:attribute name="culture">Culture.khuzait</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@color">
		<xsl:attribute name="color">FF2E7D32</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@color2">
		<xsl:attribute name="color2">FFFFD700</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff2e7d32</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffffd700</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@name">
		<xsl:attribute name="name">{=dots_kingdom_khuzait}The Reach</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_khuzait_short}Reach</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@title">
		<xsl:attribute name="title">{=dots_kingdom_khuzait_title}The Reach</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_khuzait_ruler}Warden of the South</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/@text">
		<xsl:attribute name="text">{=dots_kingdom_khuzait_desc}The Reach</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='khuzait']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.battania" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire_s" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire_w" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.sturgia" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>

	<!-- Dorne -->
	<xsl:template match="Kingdom[@id='aserai']/@owner">
		<xsl:attribute name="owner">Hero.lord_3_1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_A2</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@culture">
		<xsl:attribute name="culture">Culture.aserai</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@color">
		<xsl:attribute name="color">FFE67E22</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@color2">
		<xsl:attribute name="color2">FFC0392B</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xffe67e22</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffc0392b</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@name">
		<xsl:attribute name="name">{=dots_kingdom_aserai}Dorne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_aserai_short}Dorne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@title">
		<xsl:attribute name="title">{=dots_kingdom_aserai_title}Principality of Dorne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_aserai_ruler}Prince of Dorne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/@text">
		<xsl:attribute name="text">{=dots_kingdom_aserai_desc}Principality of Dorne</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='aserai']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.battania" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire_s" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire_w" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.sturgia" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>

	<!-- The Stormlands -->
	<xsl:template match="Kingdom[@id='empire_w']/@owner">
		<xsl:attribute name="owner">Hero.lord_1_9</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_ES1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@culture">
		<xsl:attribute name="culture">Culture.Stormlander</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@color">
		<xsl:attribute name="color">FF1C1C1C</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@color2">
		<xsl:attribute name="color2">FFE8B820</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff1c1c1c</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffe8b820</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@name">
		<xsl:attribute name="name">{=dots_kingdom_empire_w}The Stormlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_empire_w_short}Stormlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@title">
		<xsl:attribute name="title">{=dots_kingdom_empire_w_title}The Stormlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_empire_w_ruler}Lord of Storm's End</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/@text">
		<xsl:attribute name="text">{=dots_kingdom_empire_w_desc}The Stormlands</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_w']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.aserai" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.khuzait" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>

	<!-- The Vale -->
	<xsl:template match="Kingdom[@id='empire_s']/@owner">
		<xsl:attribute name="owner">Hero.lord_4_6</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@initial_home_settlement">
		<xsl:attribute name="initial_home_settlement">Settlement.town_EN1</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@culture">
		<xsl:attribute name="culture">Culture.Valeman</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@color">
		<xsl:attribute name="color">FF87CEEB</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@color2">
		<xsl:attribute name="color2">FFFFFFFF</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@primary_banner_color">
		<xsl:attribute name="primary_banner_color">0xff87ceeb</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@secondary_banner_color">
		<xsl:attribute name="secondary_banner_color">0xffffffff</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@name">
		<xsl:attribute name="name">{=dots_kingdom_empire_s}The Vale</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@short_name">
		<xsl:attribute name="short_name">{=dots_kingdom_empire_s_short}Vale</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@title">
		<xsl:attribute name="title">{=dots_kingdom_empire_s_title}The Vale of Arryn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@ruler_title">
		<xsl:attribute name="ruler_title">{=dots_kingdom_empire_s_ruler}Warden of the East</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/@text">
		<xsl:attribute name="text">{=dots_kingdom_empire_s_desc}The Vale of Arryn</xsl:attribute>
	</xsl:template>
	<xsl:template match="Kingdom[@id='empire_s']/relationships">
		<relationships>
			<relationship kingdom="Kingdom.aserai" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.empire" value="-1" isAtWar="true"/>
			<relationship kingdom="Kingdom.khuzait" value="-1" isAtWar="true"/>
		</relationships>
	</xsl:template>
</xsl:stylesheet>
