#!/usr/bin/env python3
"""Generate the DOTS faction layer for the ADOD Westeros map (Robert's Rebellion, 283 AC).

The external map module ("A Dance of Dragons - Map", Id=ADODMap) references 44 cultures and
303 owner clans in its settlements.xml. Vanilla covers 11 cultures + 74 clans; DOTS hand-authors
`Stormlander` in dots_spcultures.xml. This script generates everything else from three inputs:

  1. the map's settlements.xml            (fief ownership -> derived culture/home/tier per clan)
  2. vanilla SandBox/SandBoxCore XML      (clone templates: cultures, lords; clan->leader registry)
  3. tools/data/westeros_factions_spec.json (hand-authored politics: kingdoms, house names,
                                             rulers, rebellion wars, name pools)

Outputs (whole files, regenerate = overwrite; every file carries a GENERATED marker and is
refused if the marker is missing so hand-edits are never silently clobbered):

  Main/_Module/ModuleData/dots_adod_cultures.xml   31 culture clones (map ids verbatim)
  Main/_Module/ModuleData/characters/clans.xml     229 new clans
  Main/_Module/ModuleData/characters/lords.xml     229 leader lords (vanilla-lord clones)
  Main/_Module/ModuleData/characters/heroes.xml    229 hero rows (clan membership)
  Main/_Module/ModuleData/dots_spkingdoms.xml      custom kingdoms (Essos + Iron Islands + NW + Free Folk)
  Main/_Module/ModuleData/spclans.xslt             74 vanilla-clan retargets (name/culture/kingdom/home)
  Main/_Module/ModuleData/spkingdoms.xslt          8 vanilla-kingdom realm renames + rebellion wars
  Main/_Module/ModuleData/lords.xslt               famous vanilla-leader renames (Eddard Stark, ...)

Run:  python tools/generate_adod_factions.py            # dry-run: prints the derivation plan
      python tools/generate_adod_factions.py --apply    # write all outputs

Pattern precedents: TAOM tools/Assign-SettlementOwners.py (SPEC table, dry-run default,
fail-loud) + tools/generate_new_faction_kingdoms.py (template parametrization).
"""
import argparse
import copy
import hashlib
import json
import os
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "Main" / "_Module" / "ModuleData"
CH = MD / "characters"
SPEC_PATH = ROOT / "tools" / "data" / "westeros_factions_spec.json"

GAME = Path(os.environ.get("BANNERLORD_GAME_DIR",
                           r"E:\Steam\steamapps\common\Mount & Blade II Bannerlord"))
MAP_XML = GAME / "Modules" / "A Dance of Dragons - Map" / "ModuleData" / "settlements.xml"
SB = GAME / "Modules" / "SandBox" / "ModuleData"
SBC = GAME / "Modules" / "SandBoxCore" / "ModuleData"

MARKER = "GENERATED by tools/generate_adod_factions.py; do not hand-edit, edit the SPEC and regenerate"

# map culture id -> vanilla clone base. `Stormlander` is hand-authored in dots_spcultures.xml
# (a vlandia clone) but still needs a base here for lord/party-template lookups; culture
# EMISSION iterates missing_cultures, which excludes DOTS_HAND_CULTURES, so it is never cloned.
CULTURE_BASE = {
    "Stormlander": "vlandia",
    "Valeman": "vlandia",
    "Ironborn": "sturgia", "nightswatch": "sturgia", "Ibbenese": "sturgia", "Norvoshi": "sturgia",
    "freefolk": "battania", "Qohorik": "battania",
    "Braavosi": "empire", "Pentoshi": "empire", "Myrish": "empire", "Lyseni": "empire",
    "Tyroshi": "empire", "Lorathi": "empire", "Volantene": "empire",
    "valyrian": "empire", "Old Valyrian": "empire",
    "Dothraki": "khuzait", "Sarnori": "khuzait", "Hyrkenese": "khuzait", "Carcosans": "khuzait",
    "Lengii": "khuzait", "Yi-Tish": "khuzait", "N'ghai": "khuzait", "Shrykemen": "khuzait",
    "Ghiscari": "aserai", "Qartheen": "aserai", "Summer Islander": "aserai", "Naathi": "aserai",
    "Sothoryi": "aserai", "Asshai": "aserai", "Basilisk Corsair": "aserai",
}
CULTURE_DISPLAY = {
    "freefolk": "Free Folk", "nightswatch": "Night's Watch", "valyrian": "Valyrian",
}
VANILLA_CULTURES = {"empire", "sturgia", "aserai", "vlandia", "battania", "khuzait",
                    "forest_bandits", "sea_raiders", "steppe_bandits", "mountain_bandits",
                    "desert_bandits", "looters", "deserters", "neutral_culture", "nord",
                    "darshi", "vakken"}
DOTS_HAND_CULTURES = {"Stormlander"}  # defined in dots_spcultures.xml (renamed from `stormlands`)
VANILLA_KINGDOMS = {"empire", "empire_w", "empire_s", "sturgia", "aserai", "vlandia",
                    "battania", "khuzait"}


def slug(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def det(s, n):
    return int(hashlib.md5(s.encode()).hexdigest(), 16) % n


def strip0x(color):
    return color[2:].upper() if color.lower().startswith("0x") else color.upper()


# ---------------------------------------------------------------- parsing

def parse_map():
    """owner -> [ {type,name,culture,prosperity,id} ] for towns/castles; plus all culture refs."""
    txt = MAP_XML.read_text(encoding="utf-8", errors="replace")
    owners = defaultdict(list)
    cultures = {c.replace("Culture.", "") for c in re.findall(r'culture="(Culture\.[^"]+)"', txt)}
    for m in re.finditer(r'<Settlement ([^>]*)>\s*<Components>\s*<(Town|Village) ([^>]*)/>', txt):
        attrs, kind, comp = m.group(1), m.group(2), m.group(3)

        def g(attr, s):
            mm = re.search(attr + r'="([^"]*)"', s)
            return mm.group(1) if mm else None

        if kind == "Village":
            continue
        cul = g("culture", attrs)
        owner = g("owner", attrs)
        if not owner:
            raise SystemExit(f"fief without owner: {g('id', attrs)}")
        owners[owner.replace("Faction.", "")].append({
            "type": "castle" if 'is_castle="true"' in comp else "town",
            "name": g("name", attrs) or "?",
            "culture": (cul or "Culture.?").replace("Culture.", ""),
            "prosperity": int(g("prosperity", comp) or 0),
            "id": g("id", attrs),
        })
    # Fail loud if the map ever ships non-self-closing <Town ...>...</Town> elements the
    # fief regex would silently miss (deep-review A.4).
    town_tags = len(re.findall(r"<Town\b", txt))
    fief_total = sum(len(v) for v in owners.values())
    if town_tags != fief_total:
        raise SystemExit(f"parse_map under-count: {town_tags} <Town> tags in the map but only "
                         f"{fief_total} fiefs matched — non-self-closing Town elements?")
    # hideout owners etc. (owner attrs on non-town settlements) still must resolve
    all_owner_refs = {o.replace("Faction.", "")
                     for o in re.findall(r'owner="(Faction\.[^"]+)"', txt)}
    return owners, cultures, all_owner_refs


def parse_vanilla_clans():
    """id -> {owner_hero, culture, super_faction, name} from SandBox spclans.xml."""
    root = ET.parse(SB / "spclans.xml").getroot()
    out = {}
    for f in root.iter("Faction"):
        out[f.get("id")] = {
            "owner_hero": (f.get("owner") or "").replace("Hero.", ""),
            "culture": (f.get("culture") or "").replace("Culture.", ""),
            "super_faction": (f.get("super_faction") or "").replace("Kingdom.", ""),
            "is_bandit": f.get("is_bandit") == "true",
        }
    return out


def parse_vanilla_kingdoms():
    root = ET.parse(SB / "spkingdoms.xml").getroot()
    return {k.get("id"): k for k in root.iter("Kingdom")}


def parse_vanilla_cultures():
    root = ET.parse(SBC / "spcultures.xml").getroot()
    return {c.get("id"): c for c in root.iter("Culture")}


def parse_lord_templates(lords_path=None):
    """base culture -> {'m': Element, 'f': Element} from SandBox lords.xml (non-ruler, non-dead).

    Excludes `main_hero` (the player-character shell — first battania "Lord" in vanilla
    lords.xml) and any entry without a skill_template: those are stat-less shells, and
    cloning one produces lords with all-zero skills (deep-review H1, 2026-07-14: 21 of
    229 lords shipped as main_hero clones before this filter)."""
    root = ET.parse(lords_path or SB / "lords.xml").getroot()
    tmpl = defaultdict(dict)
    for npc in root.iter("NPCCharacter"):
        if npc.get("occupation") != "Lord" or npc.get("is_hero") != "true":
            continue
        nid = npc.get("id") or ""
        if nid.startswith("dead_") or nid == "main_hero":
            continue
        skill = npc.get("skill_template") or ""
        if not skill:
            continue
        cul = (npc.get("culture") or "").replace("Culture.", "")
        sex = "f" if npc.get("is_female") == "true" else "m"
        # prefer a non-ruler template so 229 stub lords don't all get ruler skill curves
        if sex not in tmpl[cul] or ("ruler" in (tmpl[cul][sex].get("skill_template") or "")
                                    and "ruler" not in skill):
            tmpl[cul][sex] = npc
    return tmpl


# ---------------------------------------------------------------- derivation

def derive(owners, spec, vanilla_clans):
    """Per-clan final plan: name, culture, kingdom, tier, home, leader lord, ruler name."""
    c2k = spec["culture_to_kingdom"]
    plan = {}
    pool_state = defaultdict(int)   # (culture, kind) -> next index
    used_names = defaultdict(set)
    used_rulers = defaultdict(set)

    def pool_next(culture, kind):
        pool = spec["name_pools"].get(culture)
        if not pool:
            raise SystemExit(f"no name pool for culture {culture!r}")
        items = pool["atoms"] if kind == "house" else pool["male"]
        i = pool_state[(culture, kind)]
        pool_state[(culture, kind)] += 1
        n = i // len(items)
        if n > 9:
            raise SystemExit(f"name pool for {culture!r}/{kind} exhausted after {i} draws — "
                             f"extend the pool in the SPEC")
        base = items[i % len(items)]
        suffix = "" if n == 0 else f" {'II III IV V VI VII VIII IX X'.split()[n - 1]}"
        if kind == "house":
            return pool["house_template"].format(base) + suffix
        return base + suffix

    for owner in sorted(owners):
        fiefs = owners[owner]
        cul_counts = Counter(f["culture"] for f in fiefs)
        derived_culture = cul_counts.most_common(1)[0][0]
        best = sorted(fiefs, key=lambda f: (0 if f["type"] == "town" else 1, -f["prosperity"]))[0]
        o = spec["clans"].get(owner, {})
        culture = o.get("culture", derived_culture)
        if culture not in c2k:
            raise SystemExit(f"{owner}: culture {culture!r} has no culture_to_kingdom entry")
        kingdom = o.get("kingdom", c2k[culture])
        ntowns = sum(1 for f in fiefs if f["type"] == "town")
        tier = o.get("tier", 5 if len(fiefs) >= 4 else (4 if ntowns else 3))
        is_vanilla = owner in vanilla_clans
        if owner == "mountain_bandits":
            plan[owner] = {"vanilla": True, "bandit": True,
                           "name": o.get("name", "The Mountain Clans of the Vale"),
                           "culture": None, "kingdom": None, "tier": None,
                           "home": None, "leader": None, "ruler_name": None, "female": False,
                           "fiefs": fiefs}
            continue
        name = o.get("name") or pool_next(culture, "house")
        if name in used_names[culture]:
            raise SystemExit(f"duplicate clan name {name!r} in culture {culture}")
        used_names[culture].add(name)
        ruler = o.get("ruler_name")
        if ruler:
            if ruler in used_rulers[culture]:
                raise SystemExit(f"duplicate SPEC ruler name {ruler!r} in culture {culture}")
        else:
            ruler = pool_next(culture, "male")
            while ruler in used_rulers[culture]:
                ruler = pool_next(culture, "male")
        used_rulers[culture].add(ruler)
        plan[owner] = {
            "vanilla": is_vanilla, "bandit": False,
            "name": name, "culture": culture, "kingdom": kingdom, "tier": tier,
            "tier_is_spec": "tier" in o,
            "home": best["id"], "seat": best["name"],
            "leader": vanilla_clans[owner]["owner_hero"] if is_vanilla
                      else f"lord_ADOD_{slug(owner)}_1",
            "ruler_name": ruler,
            "ruler_is_spec": bool(o.get("ruler_name")),
            "female": bool(o.get("female")),
            "color": o.get("color"), "color2": o.get("color2"),
            "fiefs": fiefs,
        }
    return plan


# ---------------------------------------------------------------- emission helpers
#
# Emitters RENDER to an in-memory staging list; nothing touches disk until every emitter
# and every validation has run (flush_outputs). This makes --apply atomic-per-run (no
# partially-regenerated repo when a later guard trips) and makes dry-run exercise the
# exact same validation paths. (Deep-review findings A.2b + A.6, 2026-07-14.)

_STAGED = []  # [(path, text)]
XSL_NS = "{http://www.w3.org/1999/XSL/Transform}"


def write_xml(path, root, apply):
    ET.indent(root, space="  ")
    body = ET.tostring(root, encoding="unicode")
    text = f"<?xml version='1.0' encoding='utf-8'?>\n<!-- {MARKER} -->\n{body}\n"
    return write_text(path, text, apply)


def write_text(path, text, apply):
    guard_overwrite(path)
    _STAGED.append((path, text))
    return path


def guard_overwrite(path):
    """Refuse to overwrite anything that isn't marker-tagged generated output or a pristine
    placeholder. Structural checks, not size/substring heuristics (deep-review A.2: the old
    len>400 / template-count<=20 heuristics silently clobbered small hand-edited files)."""
    if not path.exists():
        return
    old = path.read_text(encoding="utf-8", errors="replace")
    if MARKER in old:
        return
    try:
        root = ET.fromstring(old.lstrip("﻿"))
    except ET.ParseError:
        raise SystemExit(f"refusing to overwrite {path}: no GENERATED marker and not parseable XML")
    if path.suffix == ".xslt":
        # pristine identity stub = exactly one template, the identity copy-through
        templates = root.findall(f"{XSL_NS}template")
        if len(templates) == 1 and templates[0].get("match") == "@*|node()":
            return
        raise SystemExit(f"refusing to overwrite {path}: hand-edited XSLT (no GENERATED marker)")
    # .xml: pristine placeholder = empty root element (<Kingdoms/>, <EquipmentRosters/>, ...)
    if len(root) == 0:
        return
    raise SystemExit(f"refusing to overwrite {path}: hand-edited XML (no GENERATED marker)")


def flush_outputs():
    """Write all staged outputs: explicit CRLF bytes, no BOM (platform-independent — Path.
    write_text would translate newlines per-OS; deep-review A.1 / tools/README XML I/O)."""
    written = []
    for path, text in _STAGED:
        path.parent.mkdir(parents=True, exist_ok=True)
        data = text.replace("\r\n", "\n").replace("\n", "\r\n").encode("utf-8")
        path.write_bytes(data)
        if path.suffix in (".xml", ".xslt"):
            ET.parse(path)
        written.append(path)
    return written


# ---------------------------------------------------------------- emitters

def emit_cultures(missing_cultures, vanilla_cultures, spec, apply):
    root = ET.Element("SPCultures")
    root.append(ET.Comment(MARKER))
    c2k = spec["culture_to_kingdom"]
    for cid in sorted(missing_cultures):
        base = CULTURE_BASE.get(cid)
        if base is None:
            raise SystemExit(f"no CULTURE_BASE clone source for {cid!r}")
        el = copy.deepcopy(vanilla_cultures[base])
        s = slug(cid)
        disp = CULTURE_DISPLAY.get(cid, cid)
        k = spec["kingdoms"][c2k[cid]]
        el.set("id", cid)
        el.set("name", f"{{=dots_culture_{s}}}{disp}")
        el.set("text", f"{{=dots_culture_{s}_desc}}{disp}")
        el.set("is_main_culture", "false")
        el.set("can_have_settlement", "true")
        el.set("color", "0x" + strip0x(k["color"]).lower())
        el.set("color2", "0x" + strip0x(k["color2"]).lower())
        root.append(el)
    return write_xml(MD / "dots_adod_cultures.xml", root, apply)


def emit_clans(plan, spec, apply):
    root = ET.Element("Factions")
    root.append(ET.Comment(MARKER))
    for owner in sorted(p for p in plan if not plan[p]["vanilla"]):
        c = plan[owner]
        k = spec["kingdoms"][c["kingdom"]]
        el = ET.SubElement(root, "Faction")
        el.set("id", owner)
        el.set("name", f"{{=dots_clan_{slug(owner)}_name}}{c['name']}")
        el.set("initial_home_settlement", f"Settlement.{c['home']}")
        el.set("tier", str(c["tier"]))
        el.set("owner", f"Hero.{c['leader']}")
        el.set("culture", f"Culture.{c['culture']}")
        el.set("super_faction", f"Kingdom.{c['kingdom']}")
        el.set("is_noble", "true")
        el.set("color", strip0x(c["color"] or k["color"]))
        el.set("color2", strip0x(c["color2"] or k["color2"]))
        base = CULTURE_BASE.get(c["culture"], c["culture"])
        el.set("default_party_template", f"PartyTemplate.kingdom_hero_party_{base}_template")
    return write_xml(CH / "clans.xml", root, apply)


def emit_lords(plan, lord_templates, apply):
    root = ET.Element("NPCCharacters")
    root.append(ET.Comment(MARKER))
    for owner in sorted(p for p in plan if not plan[p]["vanilla"]):
        c = plan[owner]
        base = CULTURE_BASE.get(c["culture"], c["culture"])
        sex = "f" if c["female"] else "m"
        tmpl = lord_templates.get(base, {}).get(sex)
        if tmpl is None:
            raise SystemExit(f"no vanilla {sex} lord template for base culture {base!r}")
        el = copy.deepcopy(tmpl)
        age = 28 + det(owner, 25)
        el.set("id", c["leader"])
        el.set("name", f"{{=dots_lord_{slug(owner)}_name}}{c['ruler_name']}")
        el.set("age", str(age))
        el.set("culture", f"Culture.{c['culture']}")
        # Keep the face-morph age in sync with the assigned age when the cloned template
        # carries an explicit BodyProperties age (visual-only mismatch otherwise — H2).
        bp = el.find("./face/BodyProperties")
        if bp is not None and bp.get("age"):
            bp.set("age", str(float(age)))
        root.append(el)
    return write_xml(CH / "lords.xml", root, apply)


def emit_heroes(plan, apply):
    root = ET.Element("Heroes")
    root.append(ET.Comment(MARKER))
    for owner in sorted(p for p in plan if not plan[p]["vanilla"]):
        c = plan[owner]
        el = ET.SubElement(root, "Hero")
        el.set("id", c["leader"])
        el.set("faction", f"Faction.{owner}")
    return write_xml(CH / "heroes.xml", root, apply)


def emit_kingdoms(plan, spec, apply):
    root = ET.Element("Kingdoms")
    root.append(ET.Comment(MARKER))
    for kid, k in spec["kingdoms"].items():
        if k.get("vanilla"):
            continue
        rc = plan.get(k["ruling_clan"])
        if rc is None:
            raise SystemExit(f"kingdom {kid}: ruling clan {k['ruling_clan']!r} owns no fiefs on the map")
        el = ET.SubElement(root, "Kingdom")
        el.set("id", kid)
        el.set("owner", f"Hero.{rc['leader']}")
        el.set("initial_home_settlement", f"Settlement.{rc['home']}")
        el.set("primary_banner_color", "0x" + strip0x(k["color"]).lower())
        el.set("secondary_banner_color", "0x" + strip0x(k["color2"]).lower())
        el.set("color", strip0x(k["color"]))
        el.set("color2", strip0x(k["color2"]))
        el.set("culture", f"Culture.{k['culture']}")
        el.set("settlement_banner_mesh", "encounter_flag_a")
        el.set("flag_mesh", "info_screen_flags_b")
        s = slug(kid)
        el.set("name", f"{{=dots_kingdom_{s}}}{k['name']}")
        el.set("short_name", f"{{=dots_kingdom_{s}_short}}{k['short']}")
        el.set("title", f"{{=dots_kingdom_{s}_title}}{k['title']}")
        el.set("ruler_title", f"{{=dots_kingdom_{s}_ruler}}{k['ruler_title']}")
        el.set("text", f"{{=dots_kingdom_{s}_desc}}{k['title']}")
        pol = ET.SubElement(el, "policies")
        for p in ("policy_feudal_inheritance", "policy_castle_charters"):
            ET.SubElement(pol, "policy").set("id", p)
    return write_xml(MD / "dots_spkingdoms.xml", root, apply)


def emit_child_teen_templates(custom_cultures, apply):
    """Clone vanilla child/teenager equipment-template rosters (SandBox
    sandbox_equipment_sets.xml: 6 child + 6 teen variants per culture, incl. the
    IsLordTemplate 'noble' variants) for every custom culture. Without a culture-matching
    IsChildEquipmentTemplate/IsTeenagerEquipmentTemplate roster,
    EquipmentSelectionModel.GetEquipmentRostersForInitialChildrenGeneration returns nothing
    and HeroCreator.CreateChild NREs on new-game for that culture's lords (RCA 2026-06-02,
    pinned by ConfigIdValidationTests.ChildGenerationCultures_*). InitialChildGeneration
    iterates ALL major-faction clans, so every lord-bearing culture needs these."""
    src = ET.parse(SB / "sandbox_equipment_sets.xml").getroot()
    by_culture = defaultdict(lambda: {"child": [], "teen": []})
    for er in src.iter("EquipmentRoster"):
        fl = er.find("Flags")
        if fl is None:
            continue
        cul = (er.get("culture") or "").replace("Culture.", "")
        if fl.get("IsChildEquipmentTemplate") == "true":
            by_culture[cul]["child"].append(er)
        elif fl.get("IsTeenagerEquipmentTemplate") == "true":
            by_culture[cul]["teen"].append(er)

    child_root = ET.Element("EquipmentRosters")
    child_root.append(ET.Comment(MARKER))
    teen_root = ET.Element("EquipmentRosters")
    teen_root.append(ET.Comment(MARKER))
    for cid in sorted(custom_cultures):
        base = CULTURE_BASE[cid]
        s = slug(cid)
        pools = by_culture[base]
        if not pools["child"] or not pools["teen"]:
            raise SystemExit(f"no vanilla child/teen templates for base culture {base!r}")
        for kind, root in (("child", child_root), ("teen", teen_root)):
            for tmpl in pools[kind]:
                el = copy.deepcopy(tmpl)
                variant = el.get("id").split(f"_{base}_", 1)[1]
                el.set("id", f"dots_{kind}_template_{s}_{variant}")
                el.set("culture", f"Culture.{cid}")
                root.append(el)
    p1 = write_xml(MD / "equipmentsets" / "dots_child_equipment_templates.xml", child_root, apply)
    p2 = write_xml(MD / "equipmentsets" / "dots_lord_template_equipment.xml", teen_root, apply)
    return p1, p2


XSLT_HEAD = """<?xml version="1.0" encoding="utf-8"?>
<!-- {marker} -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
\t<xsl:output omit-xml-declaration="no" indent="yes"/>
\t<xsl:template match="@*|node()">
\t\t<xsl:copy>
\t\t\t<xsl:apply-templates select="@*|node()"/>
\t\t</xsl:copy>
\t</xsl:template>
"""


def xesc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;")


def emit_spclans_xslt(plan, vanilla_clans, apply):
    out = [XSLT_HEAD.format(marker=MARKER)]
    for owner in sorted(p for p in plan if plan[p]["vanilla"]):
        c = plan[owner]
        out.append(f'\n\t<!-- {xesc(c["name"])} -->')
        out.append(f'\t<xsl:template match="Faction[@id=\'{owner}\']/@name">')
        out.append(f'\t\t<xsl:attribute name="name">{{=dots_clan_{slug(owner)}_name}}{xesc(c["name"])}</xsl:attribute>')
        out.append("\t</xsl:template>")
        if c["bandit"]:
            continue
        if c["culture"] != vanilla_clans[owner]["culture"]:
            out.append(f'\t<xsl:template match="Faction[@id=\'{owner}\']/@culture">')
            out.append(f'\t\t<xsl:attribute name="culture">Culture.{c["culture"]}</xsl:attribute>')
            out.append("\t</xsl:template>")
        if c["kingdom"] != vanilla_clans[owner]["super_faction"]:
            out.append(f'\t<xsl:template match="Faction[@id=\'{owner}\']/@super_faction">')
            out.append(f'\t\t<xsl:attribute name="super_faction">Kingdom.{c["kingdom"]}</xsl:attribute>')
            out.append("\t</xsl:template>")
        if c.get("tier_is_spec"):
            out.append(f'\t<xsl:template match="Faction[@id=\'{owner}\']/@tier">')
            out.append(f'\t\t<xsl:attribute name="tier">{c["tier"]}</xsl:attribute>')
            out.append("\t</xsl:template>")
        out.append(f'\t<xsl:template match="Faction[@id=\'{owner}\']/@initial_home_settlement">')
        out.append(f'\t\t<xsl:attribute name="initial_home_settlement">Settlement.{c["home"]}</xsl:attribute>')
        out.append("\t</xsl:template>")
        for attr, val in (("color", c["color"]), ("color2", c["color2"])):
            if val:
                out.append(f'\t<xsl:template match="Faction[@id=\'{owner}\']/@{attr}">')
                out.append(f'\t\t<xsl:attribute name="{attr}">{strip0x(val)}</xsl:attribute>')
                out.append("\t</xsl:template>")
    out.append("</xsl:stylesheet>\n")
    return write_text(MD / "spclans.xslt", "\n".join(out), apply)


def emit_spkingdoms_xslt(plan, spec, apply):
    wars = defaultdict(set)
    for a, b in spec["wars"]:
        wars[a].add(b)
        wars[b].add(a)
    out = [XSLT_HEAD.format(marker=MARKER)]
    for kid, k in spec["kingdoms"].items():
        if not k.get("vanilla"):
            continue
        rc = plan[k["ruling_clan"]]
        s = slug(kid)
        out.append(f'\n\t<!-- {xesc(k["name"])} -->')
        for attr, val in (
            ("owner", f"Hero.{rc['leader']}"),
            ("initial_home_settlement", f"Settlement.{rc['home']}"),
            ("culture", f"Culture.{k['culture']}"),
            ("color", strip0x(k["color"])),
            ("color2", strip0x(k["color2"])),
            ("primary_banner_color", "0x" + strip0x(k["color"]).lower()),
            ("secondary_banner_color", "0x" + strip0x(k["color2"]).lower()),
            ("name", f"{{=dots_kingdom_{s}}}{k['name']}"),
            ("short_name", f"{{=dots_kingdom_{s}_short}}{k['short']}"),
            ("title", f"{{=dots_kingdom_{s}_title}}{k['title']}"),
            ("ruler_title", f"{{=dots_kingdom_{s}_ruler}}{k['ruler_title']}"),
            ("text", f"{{=dots_kingdom_{s}_desc}}{k['title']}"),
        ):
            out.append(f'\t<xsl:template match="Kingdom[@id=\'{kid}\']/@{attr}">')
            out.append(f'\t\t<xsl:attribute name="{attr}">{xesc(val)}</xsl:attribute>')
            out.append("\t</xsl:template>")
        # replace vanilla wars with Robert's Rebellion state
        out.append(f'\t<xsl:template match="Kingdom[@id=\'{kid}\']/relationships">')
        out.append("\t\t<relationships>")
        for other in sorted(wars.get(kid, ())):
            out.append(f'\t\t\t<relationship kingdom="Kingdom.{other}" value="-1" isAtWar="true"/>')
        out.append("\t\t</relationships>")
        out.append("\t</xsl:template>")
    out.append("</xsl:stylesheet>\n")
    return write_text(MD / "spkingdoms.xslt", "\n".join(out), apply)


def emit_lords_xslt(plan, apply):
    out = [XSLT_HEAD.format(marker=MARKER)]
    for owner in sorted(p for p in plan if plan[p]["vanilla"]):
        c = plan[owner]
        if c["bandit"] or not c.get("ruler_is_spec"):
            continue
        out.append(f'\n\t<!-- {xesc(c["name"])}: {xesc(c["ruler_name"])} -->')
        out.append(f'\t<xsl:template match="NPCCharacter[@id=\'{c["leader"]}\']/@name">')
        out.append(f'\t\t<xsl:attribute name="name">{{=dots_ruler_{slug(owner)}}}{xesc(c["ruler_name"])}</xsl:attribute>')
        out.append("\t</xsl:template>")
    out.append("</xsl:stylesheet>\n")
    return write_text(MD / "lords.xslt", "\n".join(out), apply)


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write outputs (default: dry-run report)")
    args = ap.parse_args()

    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    owners, map_cultures, all_owner_refs = parse_map()
    vanilla_clans = parse_vanilla_clans()
    vanilla_cultures = parse_vanilla_cultures()
    vanilla_kingdoms = parse_vanilla_kingdoms()
    lord_templates = parse_lord_templates()

    # --- coverage math
    missing_cultures = sorted(map_cultures - VANILLA_CULTURES - DOTS_HAND_CULTURES)
    unknown = [c for c in missing_cultures if c not in CULTURE_BASE]
    if unknown:
        raise SystemExit(f"cultures with no clone base: {unknown}")
    missing_owner_refs = sorted(all_owner_refs - set(vanilla_clans))
    fiefless = [o for o in missing_owner_refs if o not in owners]
    if fiefless:
        raise SystemExit(f"non-vanilla owners with no town/castle fiefs (unhandled): {fiefless}")
    for kid, k in spec["kingdoms"].items():
        if k.get("vanilla") and kid not in vanilla_kingdoms:
            raise SystemExit(f"SPEC kingdom {kid} marked vanilla but not in SandBox spkingdoms")

    plan = derive(owners, spec, vanilla_clans)

    new_clans = [o for o in plan if not plan[o]["vanilla"]]
    van_clans = [o for o in plan if plan[o]["vanilla"]]
    kingdoms_new = [k for k, v in spec["kingdoms"].items() if not v.get("vanilla")]
    used_kingdoms = {plan[o]["kingdom"] for o in plan if plan[o]["kingdom"]}
    unused = [k for k in kingdoms_new if k not in used_kingdoms]
    if unused:
        raise SystemExit(f"SPEC kingdoms with zero clans: {unused}")
    unknown_k = used_kingdoms - set(spec["kingdoms"])
    if unknown_k:
        raise SystemExit(f"clans assigned to undefined kingdoms: {sorted(unknown_k)}")

    # Every kingdom's designated ruling clan must itself land in that kingdom — the ruler's
    # clan record is what the engine uses for RulingClan. (Deep-review DF-1, 2026-07-14:
    # clan_sturgia_5 ruled Kingdom.freefolk but derived into Kingdom.battania because its
    # fiefs are mostly battania-tagged placeholders; a SPEC override fixes the data, this
    # assert makes the class of bug impossible to regenerate.)
    for kid, k in spec["kingdoms"].items():
        rc = k["ruling_clan"]
        if rc not in plan:
            raise SystemExit(f"kingdom {kid}: ruling clan {rc!r} owns no fiefs on the map")
        if plan[rc]["kingdom"] != kid:
            raise SystemExit(f"kingdom {kid}: ruling clan {rc} derived into kingdom "
                             f"{plan[rc]['kingdom']!r} — add a SPEC kingdom override for {rc}")

    print(f"map: {sum(len(v) for v in owners.values())} fiefs, {len(owners)} owners, "
          f"{len(map_cultures)} cultures")
    print(f"cultures to generate: {len(missing_cultures)}")
    print(f"new clans: {len(new_clans)}   vanilla clans retargeted: {len(van_clans)}")
    print(f"custom kingdoms: {len(kingdoms_new)}   vanilla kingdoms re-skinned: 8")
    by_k = Counter(plan[o]["kingdom"] for o in plan if plan[o]["kingdom"])
    for k in sorted(by_k):
        kk = spec["kingdoms"][k]
        rn = plan[kk["ruling_clan"]]["ruler_name"]
        print(f"  {kk['name']:24s} {by_k[k]:3d} clans  ruler: {rn} ({plan[kk['ruling_clan']]['name']})")

    # Stage ALL outputs in both modes — every emitter-level validation (missing templates,
    # ruling-clan fiefs, overwrite guards) runs on dry-run too; disk is only touched by
    # flush_outputs() under --apply, after everything has passed (atomic-per-run).
    emit_child_teen_templates(set(missing_cultures) | DOTS_HAND_CULTURES, args.apply)
    emit_cultures(missing_cultures, vanilla_cultures, spec, args.apply)
    emit_clans(plan, spec, args.apply)
    emit_lords(plan, lord_templates, args.apply)
    emit_heroes(plan, args.apply)
    emit_kingdoms(plan, spec, args.apply)
    emit_spclans_xslt(plan, vanilla_clans, args.apply)
    emit_spkingdoms_xslt(plan, spec, args.apply)
    emit_lords_xslt(plan, args.apply)

    if not args.apply:
        print("\n-- dry-run. Per-clan plan sample (20):")
        for o in sorted(plan)[:20]:
            c = plan[o]
            tag = "VAN" if c["vanilla"] else "NEW"
            print(f"  [{tag}] {o:38s} {c['name']:38s} {str(c['culture']):16s} -> {c['kingdom']}")
        print(f"\nAll {len(_STAGED)} outputs staged + validated in memory. "
              "Run with --apply to write.")
        return

    for p in flush_outputs():
        print(f"  wrote {p.relative_to(ROOT)}")
    print("Done. Next: python tools/audit_adod_map_refs.py && python tools/validate_moduledata.py")


if __name__ == "__main__":
    main()
